### PR TITLE
Added HealthCheck groups 

### PR DESCRIPTION
**Pull request by JuergenGutsch**
Added HealthCheck groups to group multiple checks to a single check as discussed in the old repository: https://github.com/aspnet/AspLabs/issues/13

Grouping may help to handle a group of checks in a different way than another group or than single checks. 

A similar PR is already in the old repository. The HealthCheckResult changed a little bit and the new CompositeHealthCheckResult makes the grouping a lot easier. This is why the AddHealthCheckGroup extension method now is much smaller, than in the old PR :)

ASP.NET Core
image

ASP.NET
image

### CODE REVIEW

**Comment by ycrumeyrolle** [comment]
I prefer the term of tags instead of groups., a check may be present in differents groups. 
For example I may want to have groups of checks for every functional domain in may application (payment, orders, sales, ...) and groups of checks for every technical aspect (certificates, web services, database, cache, ...). Such tags allow to groups results, the purpose of this PR.
Thoughts @JuergenGutsch ?

**Comment by JuergenGutsch** [comment]
At the end it's just a term. As you wrote, the term "Tags" makes sense too, but I think "Groups" describes it a little more generic and is a little more understandable for the majority of the devs.  IMHO

**Comment by damienbod** [comment]
@bradwilson @glennc Would be cool to have this feature.

**Comment by bradwilson** [comment]
Thanks for the PR!

We're going to accept this, but I need to do some work to it (to adapt to recent changes in the code base as well as introduce parallelism). No effort required on your end. :)

**Comment by JuergenGutsch** [comment]
Great. Thanks :)

**Pull request merged**
